In [4]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
# import tensorflow_datasets as tfds
from tensorflow.keras import layers
import tensorflow as tf
from tensorflow import keras
# import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
import numpy as np
import os, keras
from sklearn.preprocessing import RobustScaler,StandardScaler, LabelEncoder, OneHotEncoder
import cv2

In [5]:
def load_images(directory, uniq_labels):
    images = []
    labels = []
    for idx, label in enumerate(uniq_labels):
        print(label," is ready to load")
        for file in os.listdir(directory + "/" + label):
            filepath = directory + "/" + label + "/" + file
            image = cv2.resize(cv2.imread(filepath), (64, 64))
            images.append(image)
            labels.append(idx)
    images = np.array(images)
    labels = np.array(labels)
    return(images, labels)

In [6]:
train_dir = "sl_alphabet/asl_alphabet_train/asl_alphabet_train"

uniq_labels = sorted(os.listdir(train_dir))
# print(uniq_labels)
images, labels = load_images(directory = train_dir, uniq_labels =uniq_labels)
print("Data has been loaded")

A  is ready to load
B  is ready to load
C  is ready to load
D  is ready to load
E  is ready to load
F  is ready to load
G  is ready to load
H  is ready to load
I  is ready to load
J  is ready to load
K  is ready to load
L  is ready to load
M  is ready to load
N  is ready to load
O  is ready to load
P  is ready to load
Q  is ready to load
R  is ready to load
S  is ready to load
T  is ready to load
U  is ready to load
V  is ready to load
W  is ready to load
X  is ready to load
Y  is ready to load
Z  is ready to load
del  is ready to load
nothing  is ready to load
space  is ready to load
Data has been loaded


In [8]:
# print(images)
# print(labels.size)
print(images.shape)

(87000, 64, 64, 3)


In [9]:
IMG_SIZE = (64, 64)
SIZE = 64
BATCH_SIZE = 128

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    validation_split=0.2,  # Reserve 20% of the data for validation
    subset="training",     # This indicates that we're creating the training subset
    seed=123,              # Random seed for shuffling and splitting
    image_size=IMG_SIZE, # Resize images to 256x256
    batch_size=BATCH_SIZE,   # Number of images per batch
    color_mode='rgb',
    label_mode='categorical'
)

# Load validation dataset with validation split
val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    validation_split=0.2,  # Reserve 20% of the data for validation
    subset="validation",   # This indicates that we're creating the validation subset
    seed=123,              # Random seed for shuffling and splitting (must be the same as for training)
    image_size=IMG_SIZE, # Resize images to 256x256
    batch_size=BATCH_SIZE,          # Number of images per batch
    color_mode='rgb',
    label_mode='categorical'
)


Found 87000 files belonging to 29 classes.
Using 69600 files for training.
Found 87000 files belonging to 29 classes.
Using 17400 files for validation.


In [10]:
test_dir = 'sl_alphabet/asl_alphabet_test'
test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    test_dir,  
    seed=123,     
    batch_size=BATCH_SIZE,        
    image_size=IMG_SIZE,         
    color_mode='rgb',
    label_mode='categorical',
    shuffle = False
)


Found 28 files belonging to 1 classes.


In [11]:
data = train_ds.take(1)
for x , y in data:
    print(x.shape)
    print(y[10])
# print(x)
# print(y)

(128, 64, 64, 3)
tf.Tensor(
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.], shape=(29,), dtype=float32)


In [19]:
resize_and_rescale = tf.keras.Sequential([
  layers.Resizing(SIZE, SIZE),
  layers.Rescaling(1./255)
])

In [56]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_16 (Conv2D)              │ (None, 62, 62, 64)     │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 31, 31, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_17 (Conv2D)              │ (None, 29, 29, 32)     │        18,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_18 (Conv2D)              │ (None, 12, 12, 16)     │         4,624 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_15 (MaxPooling2D) │ (None, 6, 6, 16)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_6 (Flatten)             │ (None, 576)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 64)             │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 29)             │           957 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64,845 (253.30 KB)

 Trainable params: 64,845 (253.30 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model = tf.keras.models.Sequential([
    
    
    tf.keras.layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu', input_shape=(SIZE,SIZE,3)),
	# resize_and_rescale,
    tf.keras.layers.MaxPooling2D(pool_size=2),

    tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu'),
	
    tf.keras.layers.MaxPooling2D(pool_size=2),

    tf.keras.layers.Conv2D(filters=16, kernel_size=(3,3), activation='relu'),

    tf.keras.layers.MaxPooling2D(pool_size=2),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    # tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(units=29, activation='softmax')

	])

In [28]:
base_learning_rate = 0.0001
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=base_learning_rate),
              loss=tf.keras.losses.CategoricalCrossentropy (),
              metrics=['accuracy'])

In [29]:
# model.compile(optimizer='adam',
#               loss='categorical_crossentropy',
#               metrics=['accuracy'])

In [30]:
history = model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=10
)

Epoch 1/10
 24/544 ━━━━━━━━━━━━━━━━━━━━ 3:06 359ms/step - accuracy: 0.0319 - loss: 48.8021

KeyboardInterrupt: 

In [61]:
base_model = tf.keras.applications.MobileNetV2(input_shape=(SIZE, SIZE, 3),
                                               include_top=False,
                                               weights='imagenet')

C:\Users\Nada Ayman\AppData\Local\Temp\ipykernel_11548\1526215721.py:1: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  base_model = tf.keras.applications.MobileNetV2(input_shape=(SIZE, SIZE, 3),


9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [62]:
base_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [63]:
# history = model.fit(train_ds, epochs=10, validation_data=val_ds)

Epoch 1/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 199s 366ms/step - accuracy: 0.7485 - loss: 0.7393 - val_accuracy: 0.8333 - val_loss: 0.5250
Epoch 2/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 193s 354ms/step - accuracy: 0.7773 - loss: 0.6488 - val_accuracy: 0.8603 - val_loss: 0.4443
Epoch 3/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 245s 451ms/step - accuracy: 0.8042 - loss: 0.5756 - val_accuracy: 0.8701 - val_loss: 0.4004
Epoch 4/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 243s 446ms/step - accuracy: 0.8264 - loss: 0.5113 - val_accuracy: 0.8945 - val_loss: 0.3354
Epoch 5/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 261s 479ms/step - accuracy: 0.8434 - loss: 0.4543 - val_accuracy: 0.9128 - val_loss: 0.2883
Epoch 6/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 206s 378ms/step - accuracy: 0.8590 - loss: 0.4096 - val_accuracy: 0.9125 - val_loss: 0.2789
Epoch 7/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 237s 436ms/step - accuracy: 0.8733 - loss: 0.3622 - val_accuracy: 0.9229 - val_loss: 0.2441
Epoch 8/10
544/544 ━━━━━━━━━━━━━━━━━━━━ 237s 435ms/step - accuracy: 0.8850 -

In [66]:
model.save('model_2.h5')

In [2]:
for x, y in test_ds.take(1):
    print(x.shape)

NameError: name 'test_ds' is not defined

In [76]:
x

<tf.Tensor: shape=(28, 64, 64, 3), dtype=float32, numpy=
array([[[[  1.0117188 ,   0.6953125 , 225.34766   ],
         [  8.921875  ,   8.3359375 , 182.41016   ],
         [ 12.046875  ,   9.605469  , 183.04688   ],
         ...,
         [ 14.980469  ,   9.917969  , 183.63281   ],
         [ 12.1640625 ,   8.328125  , 184.94922   ],
         [  7.84375   ,   8.105469  , 204.15234   ]],

        [[ 13.113281  ,  14.050781  , 182.14844   ],
         [159.09375   , 138.1289    , 108.53125   ],
         [139.9336    , 121.01172   ,  98.05859   ],
         ...,
         [127.03516   , 106.23828   ,  93.60156   ],
         [113.609375  ,  94.38672   ,  87.609375  ],
         [ 89.54297   ,  78.09375   , 150.28125   ]],

        [[  9.558594  ,  10.96875   , 186.34766   ],
         [ 95.89453   ,  96.38672   ,  84.94141   ],
         [109.50781   , 110.03516   ,  99.07031   ],
         ...,
         [120.359375  , 102.5       ,  86.5       ],
         [123.52344   , 105.59375   ,  90.58594  

In [77]:
predictions = model.predict(x)
predicted_class = np.argmax(predictions, axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step


In [78]:
predicted_class

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28], dtype=int64)